<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE pedidos[
<!ELEMENT pedidos (cliente|articulo|pedido)+>
<!ELEMENT cliente (nombre, apellidos)>
<!ATTLIST cliente idCliente CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT articulo (nombre, descripcion)>
<!ATTLIST articulo refArticulo CDATA #REQUIRED>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT pedido (articuloPedido, metodoPago, direccion)>
<!ATTLIST pedido idPedido CDATA #REQUIRED>
<!ATTLIST pedido idCliente CDATA #REQUIRED>
<!ELEMENT articuloPedido (#PCDATA)>
<!ATTLIST articuloPedido precio CDATA #REQUIRED>
<!ATTLIST articuloPedido refArticulo CDATA #REQUIRED>
<!ELEMENT metodoPago (tarjeta)>
<!ELEMENT tarjeta (numero, fechaCaducidad, banco)>
<!ATTLIST tarjeta titular CDATA #REQUIRED>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT fechaCaducidad (#PCDATA)>
<!ELEMENT banco (#PCDATA)>
<!ELEMENT direccion  (provincia, poblacion, calle, numero)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT calle (#PCDATA)>
]>


<pedidos>
      <cliente idCliente="cli01">
            <nombre>Luz</nombre>
            <apellidos>PeÃÅrez</apellidos>
      </cliente>

      <cliente idCliente="cli02">
            <nombre>Miranda</nombre>
            <apellidos>Gabriel</apellidos>
      </cliente>
      <articulo idArticulo="art01">
            <nombre>papas</nombre>
            <descripcion>saco de papas</descripcion>
      </articulo>
      <articulo idArticulo="art02">
            <nombre>boniatos</nombre>
            <descripcion>saco de batatas</descripcion>
      </articulo>
      <pedido idPedido="ped01" idCliente="cli01">
            <articuloPedido precio="1001" refArticulo="art01"></articuloPedido>
            <metodoPago>
                  <tarjeta titular="cli01">
                        <numero>123456789</numero>
                        <fechaCaducidad>01-01-2018</fechaCaducidad>
                        <banco></banco>
                  </tarjeta>
            </metodoPago>
            <direccion>
                  <provincia></provincia>
                  <poblacion></poblacion>
                  <calle></calle>
                  <numero></numero>
            </direccion>
      </pedido>
      <pedido idPedido="ped02" idCliente="cli02">
            <articuloPedido precio="1002" refArticulo="art02"></articuloPedido>
            <metodoPago>
                  <tarjeta titular="cli02">
                        <numero></numero>
                        <fechaCaducidad></fechaCaducidad>
                        <banco></banco>
                  </tarjeta>
            </metodoPago>
            <direccion>
                  <provincia></provincia>
                  <poblacion></poblacion>
                  <calle></calle>
                  <numero></numero>
            </direccion>
      </pedido>
      <pedido idPedido="ped03" idCliente="cli02">
            <articuloPedido precio="1003" refArticulo="art02"></articuloPedido>
            <metodoPago>
                  <tarjeta titular="cli02">
                        <numero></numero>
                        <fechaCaducidad></fechaCaducidad>
                        <banco></banco>
                  </tarjeta>
            </metodoPago>
            <direccion>
                  <provincia></provincia>
                  <poblacion></poblacion>
                  <calle></calle>
                  <numero></numero>
            </direccion>
      </pedido>
</pedidos>
